name: Build and Analyze

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: v14
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm run format-check
